### ISSUE TITLE
editing 'has' of scripts doesn't update

### ISSUE THREAD

**Issue by modgethanc** [vilmibm/tildemush#153] opened 2018-09-17 18:26 UTC
in trying to change descriptions/names of things, it doesn't seem to update what's actually displayed? i can modify a description and see the modified version in a subsequent edit, but it doesn't show up in /look data.

**Comment by vilmibm** [comment] 2018-09-25 17:32
duplicate of #62

**Closed by vilmibm** 2018-09-25 17:32 UTC
